covidify/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('rapidTest.urls')),
    path('', include('qna.urls')),
    path('', include('list_rs.urls')),
    path('', include('health_protocol.urls')),
]

qna/urls.py
from django.urls import path

from . import views

app_name = 'qna'

urlpatterns = [
     path('qna/',views.forum,name='forum'),
     path('lihatPertanyaan/',views.lihatPertanyaan,name='lihatPertanyaan'),
     path('balas/<int:komen_id>/' ,views.balas, name='balas'),
]

qna/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class pertanyaan(models.Model):
    penanya = models.CharField(max_length=400)
    pertanyaan = models.TextField(max_length=800)
    location = models.TextField(max_length=400,default="Depok")
    time = models.DateTimeField(default=timezone.now)
    
    def __str__(self):
        return "{} | {} ".format(self.penanya,self.pertanyaan)

class komentar(models.Model):
    pengomentar = models.CharField(max_length=400)
    komen = models.TextField(max_length =800)
    tanya = models.ForeignKey(pertanyaan, on_delete = models.CASCADE)
    time = models.DateTimeField(default=timezone.now)
    location = models.TextField(max_length=400, default="Depok")

    def __str__(self):
        return "{} | {} | {} ".format(self.tanya.pertanyaan,self.pengomentar,self.komen)

qna/forms.py
from django import forms
from .models import *

class pertanyaanForm(forms.ModelForm):
    class Meta :
        model = pertanyaan
        fields =[

            'penanya','location','pertanyaan'
        ]
        labels = {'penanya':'From ','pertanyaan':'Pertanyaan :','location':'Location :'}
        widgets ={
            'penanya': forms.TextInput(attrs={'class':'form-control','placeholder': "Put your name here"}),
            'location': forms.TextInput(attrs={'class':'form-control','placeholder': "Put your location here"}),
            'pertanyaan': forms.Textarea(attrs={'class':'form-control','cols': 140,'rows': 10, 'placeholder': "Put your answer here"})
            }

class komenForm(forms.ModelForm):
    class Meta :
        model = komentar
        fields =['pengomentar','location','komen']
        labels = {'pengomentar':'From :','komen':'Balasan :','location':'Location :'}
        widgets ={
            'pengomentar': forms.TextInput(attrs={'class':'form-control','placeholder': "Put your name here",  "autocomplete":"off"}),
            'location': forms.TextInput(attrs={'class':'form-control','placeholder': "Put your location here"}),
            'komen': forms.Textarea(attrs={'class':'form-control','cols': 10,'rows': 10, 'placeholder': "Put your answer here",  "autocomplete":"off"}), 
            }

qna/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import *
from django.http.response import HttpResponseRedirect

def forum(request):
    pertanyaan_form = pertanyaanForm(request.POST or None)
    if request.method == 'POST':
        if pertanyaan_form.is_valid():
            pertanyaan_form.save()
            listpertanyaan = pertanyaan.objects.all()
            context ={
                'status':1, 'pertanyaan':listpertanyaan
            }

            return render(request,'forum.html',context)

    context ={
            'page_title':'Forum Keluarga',
            'pertanyaan_form':pertanyaan_form, 'status':2
    }
    return render(request,'forum.html',context)
    

def lihatPertanyaan(request):
    listpertanyaan = pertanyaan.objects.all()
    
    context = {'page_title':'Forum Keluarga',
    'pertanyaan':listpertanyaan, 'status' :1
    }   

    return render(request,'forum.html',context)


def balas(request,komen_id):
    balasan = komentar.objects.all()
    listPertanyaan = pertanyaan.objects.get(id=komen_id)
    balasan_form = komenForm(request.POST or None)
    b=0
    for a in balasan :
        if a.tanya == listPertanyaan :
            b = b+1
    context = {
        'list_balasan' : balasan, 'pertanyaan':listPertanyaan,
        'form_balasan' : balasan_form, 'count':b
    }
    if request.method == 'POST' :
        if balasan_form.is_valid():
            balasan.create(
                pengomentar = balasan_form.cleaned_data.get('pengomentar'),
                komen = balasan_form.cleaned_data.get('komen'),
                location =  balasan_form.cleaned_data.get('location'),
                tanya = listPertanyaan
            )
            return redirect('qna:balas', komen_id=komen_id)
            
    return render(request,'forum-pertanyaan.html',context)
            
    

qna/templates/forum-pertanyaan.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<header>
    <link rel="stylesheet" href="{% static 'css/qna.css' %}"/>
    <div class="cover-qna" >
    </div>
</header>
{% endblock meta %}

{% block content %}
<br> <br>
    <h3>
      <center> <b> LETS DISCUSS ABOUT COVID </b></center>
    </h3>
<br/>

<div>
<div class="container">
    <div>
        <a href="{%url 'qna:lihatPertanyaan'%}" class="btn btn-danger">Back</a>
    </div>
    <br>
                
                <div class="card card-qna">
                        <div class="border-bottom border-light"><b>{{pertanyaan.penanya}}</b> </div>
                        <div>{{pertanyaan.pertanyaan}}</div>
                        <div class="small">{{pertanyaan.location}} on {{pertanyaan.time}}</div>
                      
                    <nav class="navbar navbar-inverse">
                        <div class="nav"></div>
                            <div class="nav">
                                
                                <a class="btn btn-qna3" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
                                    Reply
                                </a>
                            </div>
                    </nav>  
                </div>     
</div>
<br>

<div class="collapse" id="collapseExample">
    <div class="container">
        <div class="card card-qna">
                <div class="container-sm ">
                    <div class="form-group">
                        <form method="POST">
                            {% csrf_token %}
                            {{form_balasan.as_p}}
                            <nav class="navbar navbar-inverse">
                                <div class="nav navbar">

                                </div>
                                <div class="nav navbar">
                                        <button class="btn btn-qna3" type="submit" >Post Now</button>
                                    </div>
                            </nav>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
<br>

<script>
    $(document).ready( function () {
        $('#ktable').DataTable({
            "dom": 'rtp',
            "scrollY": "500px",
            "scrollCollapse": true,
            "paging": false,
            "ordering" : false,
        });
    });
</script>
{% if count > 0 %}
<div class="container">
        <table id="ktable" class="table border-0">
            <thead>
                <th class="table border-0">View all {{count}} comments</th>
            </thead>
            <tbody>
                {%for i in list_balasan %}
                {%if i.tanya == pertanyaan %}
                <tr class=" table border-0">
                    <td>
                    <div>
                                <div class="card card-komen">
                                    <div class="border-bottom border-dark"><b>{{i.pengomentar}}</b> </div>
                                    <div class=>{{i.komen}}</div>
                                    <div class= "small">{{i.location}} on {{i.time}}</div>   
                        </div> 
                    </div>
                    </td>
                </tr>
            {%endif %}   
            {%endfor %} 
        </tbody>
        </table>
</div>
{% endif %}
    

{% endblock content %}

qna/templates/forum.html
{% extends 'base.html' %}
{% load static %}


{% block meta %}
<header>
    <link rel="stylesheet" href="{% static 'css/qna.css' %}"/>
    <div class="cover-qna" >
    </div>
</header>
{% endblock meta %}
{% block content %}

<br> <br>
<center>
    <h3>
       <b> LETS DISCUSS ABOUT COVID</b>
    </h3>
</center>


<script>
    $(document).ready( function () {
        $('#ptable').DataTable({
                "iDisplayLength": 4,
                "ordering" : false,
                "dom": 'frtp',
        });
    });
</script>



<div class="container">
    {%if status == 1 %}
    <nav class="navbar">
    <div></div>
    <a href="{% url 'qna:forum' %}" class="btn btn-qna">Add Question</a>
    </nav>
{%endif %}

{%if status == 1 %}
<div class="container">
    <section>
    <table id ="ptable" class="table border-0" >
        <thead>
            <th class="table border-0">
            </th>
        </thead>
        <tbody>
            {%for i in pertanyaan %}
            <tr>
                <td>
                    <div class="card card-qna" style="background-color:#232065;">
                        <div class=" border-bottom border-light"><b>{{i.penanya}}</b> </div>
                        <div>{{i.pertanyaan}}</div>
                        <div class="small">{{i.location}} on {{i.time}}</div>
                        
                    <nav class="navbar navbar-inverse">
                    <div class="nav"></div>
                    <div class="nav">
                        <a href="{% url 'qna:balas' komen_id=i.id %}" class="btn btn-qna2">Open</a> 
                    </div>
                    </nav>
                
                </div>
                <br>
                </td>
            </tr>
            {%endfor %}
        </tbody>
    </table>
</section>
</div>
{% endif %}



{%if status == 2 %}
<center>
    <table>
    <tr>
        <td>
            <div class="form-group container">
                <div class="card qnabox" style="color: white;">
                <form method="POST" action="{%url 'qna:forum' %}">
                    {% csrf_token %}
                    {{pertanyaan_form.as_p}}
            </div>
            <nav class="navbar">
             <div></div> 
             <div class="nav navbar "> 
            <table>
                <tr>
                    <td>
                        <a href="{%url 'qna:lihatPertanyaan'%}" class=" nav navbar btn btn-danger">Back </a>
                    </td>
                    <td>
                        <button class="nav navbar btn btn-qna" type="Submit"> Post </button>
                    </td>
                </tr>
        
            </table>
        </div> 
            </nav>  
        </form>
            </div>
        </td>
    </tr>
    </table>

</center>

{% endif %}
{% endblock content %}