covidify/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('rapidTest.urls')),
    path('', include('qna.urls')),
    path('', include('list_rs.urls')),
    path('', include('health_protocol.urls')),
]

qna/urls.py
from django.urls import path

from . import views

app_name = 'qna'

urlpatterns = [
     path('qna/',views.forum,name='forum'),
     path('lihatPertanyaan/',views.lihatPertanyaan,name='lihatPertanyaan'),
     path('balas/<int:komen_id>/' ,views.balas, name='balas'),
]

rapidTest/urls.py
from django.urls import path
from . import views

app_name = 'rapidTest'

urlpatterns = [
    path('rapidTest/', views.rapidTest, name='rapid'),
    path('formRapid/', views.form_Rapid, name='form'),
]

rapidTest/models.py
from django.db import models

# Create your models here.

class Rapid(models.Model):
    nama_tempat = models.CharField(max_length=100)
    tanggal_pelaksanaan_mulai = models.DateField(auto_now_add=False, auto_now=False, null=True)
    tanggal_pelaksanaan_akhir = models.DateField(auto_now_add=False, auto_now=False, null=True)
    biaya = models.DecimalField(max_digits=6, decimal_places=3)
    alamat = models.TextField()

rapidTest/forms.py
from django import forms
from .models import Rapid
from functools import partial

DateInput = partial(forms.DateInput, {'class': 'datepicker'})

class FormRapid(forms.ModelForm):
    class Meta:
        model = Rapid
        fields = [
            'nama_tempat', 
            'tanggal_pelaksanaan_mulai', 
            'tanggal_pelaksanaan_akhir',
            'biaya', 
            'alamat', 
        ] 
            
    nama_tempat = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Ex: RS Kasih Ibu'}))
    tanggal_pelaksanaan_mulai = forms.DateField(widget=DateInput())
    tanggal_pelaksanaan_akhir = forms.DateField(widget=DateInput())
    biaya = forms.DecimalField(min_value=0, widget=forms.NumberInput(attrs={'placeholder': 'Max: 999.999'}))  

rapidTest/views.py
from django.shortcuts import render
from .models import Rapid
from .forms import FormRapid
from django.http import HttpResponseRedirect

# Create your views here.

def rapidTest(request):
    obj = Rapid.objects.all() 
    context = {'obj': obj}
    return render(request, 'rapidTest/rapidTest.html', context)

def form_Rapid(request):
    form = FormRapid(request.POST or None)
   
    if (form.is_valid() and request.method == 'POST'):
        form.save()       
        return HttpResponseRedirect('/rapidTest')

    context = {'form': form}
    
    return render(request, 'rapidTest/formRapid.html', context)


    

rapidTest/templates/rapidTest/formRapid.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<link href="{% static 'js/jquery-ui-1.12.1/jquery-ui.min.css' %}" rel="stylesheet">
<link href="{% static 'js/jquery-ui-1.12.1/jquery-ui.structure.min.css' %}" rel="stylesheet">
<link href="{% static 'js/jquery-ui-1.12.1/jquery-ui.theme.min.css' %}" rel="stylesheet">
 
<script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
<script src="{% static 'js/jquery-ui-1.12.1/jquery-ui.min.js' %}"></script>
<script src="{% static 'js/myjs.js' %}"></script>

<header>
  <link rel="stylesheet" href="{% static 'css/rapidTest.css' %}"/>
</header>
{% endblock meta %}

{% block content %}
<div class = "cover2"></div>
<h2 class = "judul">TAMBAH TEMPAT RAPID TEST</h2>

<section>
  <div class="container-fluid ">
    <div class = "row">
      <div class="col-sm-12 d-flex justify-content-center" style = "text-align:center">
        <div class="card" style="width: 30rem; background-color:#FFFFFF">
          <div class="card-header">
            <div class="card-body">
                        
              <form action="" method="POST" autocomplete="off" class='d-flex justify-content-center'>
                <div class="form-row align-items-center">
                  <div class="col-auto">
                    
                    {% csrf_token %}
                    <h5 class="form-fld">Nama Tempat</h5>
                    <div class="d-flex justify-content-center">{{form.nama_tempat}}</div>
                    <h5 class="form-fld">Tanggal Pelaksanaan</h5>
                    <h8 class="form-fld">(mulai)</h8>
                    <div class="d-flex justify-content-center">{{form.tanggal_pelaksanaan_mulai}}</div>
                    <h8 class="form-fld">(akhir)</h8>
                    <div class="d-flex justify-content-center">{{form.tanggal_pelaksanaan_akhir}}</div>
                    <h5 class="form-fld">Biaya</h5>
                    <div class="d-flex justify-content-center">{{form.biaya}}</div>
                    <h5 class="form-fld">Alamat</h5>
                    <div class="d-flex justify-content-center">{{form.alamat}}</div>
                    <br>

                    <button style= "background-color: #DF6357" type="submit" class="btn btn-danger btn-lg">Add</button>
                  </div>
                </div>
              </form>

              <!-- Tombol ke halaman daftar tempat rapid test -->
              <a class="btn btn-danger btn-lg" style= "background-color: #DF6357" href="{% url 'rapidTest:rapid' %}" role="button">Back</a>                            
            
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

rapidTest/templates/rapidTest/rapidTest.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<header>
  <link rel="stylesheet" href="{% static 'css/rapidTest.css' %}"/>
</header>
{% endblock meta %}

{% block content %}
<div class = "cover2"></div>
<h2 class = "judul">DAFTAR TEMPAT RAPID TEST</h2>

  <!-- DataTable -->
  <script>
    $(document).ready(function() {
      $('#rapidTest').DataTable({
          "aLengthMenu":[[3, 5, 10, 25], [3, 5, 10, 25]],
            "iDisplayLength":3,
            "ordering":false,         
      });
    });
  </script>

 <!-- Tabel Daftar Tempat Rapid Test -->
  <div id="tabel">  
    <div class="container-fluid">
      <div class="table-responsive-md">
 
        <table id="rapidTest" class="table table-striped" >
          <thead>
            <tr style="background-color: #DF6357;color: white;"> 
              <th id="nama" class="text-center" scope="col">Nama Tempat</th>
              <th id="tanggal" class="text-center" scope="col">Tanggal Pelaksanaan</th>
              <th id="biaya" class="text-center" scope="col">Biaya</th>
              <th id="alamat" class="text-center" scope="col">Alamat</th>   
            </tr>
          </thead>

          <!-- Menampilkan data dengan loop data dari obj yang ada di views -->
          <tbody>
            {% for i in obj %} 
            <tr>        
              <th class="text-center" scope="row">{{i.nama_tempat}}</th>
              <td class="text-center">{{i.tanggal_pelaksanaan_mulai}} - {{i.tanggal_pelaksanaan_akhir}}</td>
              <td class="text-center">{{i.biaya}}</td>
              <td class="text-center">{{i.alamat}}</td>           
            </tr>
            {% endfor %}
          </tbody>

         </table>
      </div>
    
      <!-- Tombol Add yang me-refer ke halaman form -->
      <div class="d-flex justify-content-end" id="btn-add1">
        <a href="{% url 'rapidTest:form' %}">
          <button type="button" class="btn btn-light btn-lg" style="background-color: #DF6357;color: white;">Add</button>
        </a>
    </div>

    </div>                        
  </div>

{% endblock content %}