covidify/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('rapidTest.urls')),
    path('', include('qna.urls')),
    path('', include('list_rs.urls')),
    path('', include('health_protocol.urls')),
]

health_protocol/urls.py
from django.urls import path
from .views import index, alternatives, upvote, downvote

app_name = 'health_protocol'

urlpatterns = [
    path('health_protocol/', index, name='healthProtocol'),
    path('alternatives/', alternatives, name='alternatives'),
    path('upvote/<int:pk>', upvote, name='upvote'),
    path('downvote/<int:pk>', downvote, name='downvote'),
]

list_rs/urls.py
from django.urls import path
from .views import tambahRS, listRS
app_name = 'list_rs'
urlpatterns = [
    path('tambahRS/',tambahRS, name='tambahRS'),
    path('listRS/',listRS,name = 'listRS'),
    
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('feedbacks',views.listFeedback, name='feedbacklist'),
    path('formFeedback',views.formFeedback, name='feedbackform')
]

qna/urls.py
from django.urls import path

from . import views

app_name = 'qna'

urlpatterns = [
     path('qna/',views.forum,name='forum'),
     path('lihatPertanyaan/',views.lihatPertanyaan,name='lihatPertanyaan'),
     path('balas/<int:komen_id>/' ,views.balas, name='balas'),
]

rapidTest/urls.py
from django.urls import path
from . import views

app_name = 'rapidTest'

urlpatterns = [
    path('rapidTest/', views.rapidTest, name='rapid'),
    path('formRapid/', views.form_Rapid, name='form'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">


<head>
  <title>Covidify</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}"/>
  <link rel = "icon" type = "image/png" href = "{% static 'image/Group94.png' %}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.css">
  <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.js"></script>
  
  <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
</head>


<nav class="navbar navbar-expand-md navbar-dark" style="background-color: rgba(44, 23, 93); font-family: 'Poppins', sans-serif;">
  <a class="navbar-brand" href="{% url 'main:home' %}" style="color: #EC6542;">Covidify</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>
    <div class="collapse navbar-collapse " id="collapsibleNavbar">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'health_protocol:healthProtocol' %}" style="color: white;">Health Protocol</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'list_rs:listRS' %}" style="color: white;">Hospital</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'rapidTest:rapid' %}" style="color: white;">Rapid Test</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'qna:lihatPertanyaan' %}" style="color: white;">QnA</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:feedbacklist' %}" style="color: white;">Feedback</a>
        </li>
      </ul>
    </div>
</nav>
{% block meta %}


{% endblock meta %}
<body >
  {% block content %}
  {% endblock content %}
</body>

</html>