covidify/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('rapidTest.urls')),
    path('', include('qna.urls')),
    path('', include('list_rs.urls')),
    path('', include('health_protocol.urls')),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('feedbacks',views.listFeedback, name='feedbacklist'),
    path('formFeedback',views.formFeedback, name='feedbackform')
]

qna/urls.py
from django.urls import path

from . import views

app_name = 'qna'

urlpatterns = [
     path('qna/',views.forum,name='forum'),
     path('lihatPertanyaan/',views.lihatPertanyaan,name='lihatPertanyaan'),
     path('balas/<int:komen_id>/' ,views.balas, name='balas'),
]

main/models.py
from django.db import models

# Create your models here.

class Feedback(models.Model):
    nama = models.CharField(max_length=100)
    feedbackUser = models.TextField(max_length=1000)
    

main/forms.py
from django import forms
from .models import Feedback

class FeedbackForm(forms.ModelForm):
    nama = forms.CharField(label="Nama :")
    feedbackUser = forms.CharField(widget=forms.Textarea, label='Feedback :')
    class Meta:
        model = Feedback
        fields = '__all__'

main/views.py
from django.shortcuts import render,get_object_or_404, redirect
from django.http import HttpResponse, Http404
import requests
import json
from .models import *
from .forms import *

def home(request):
    url = "https://covid-193.p.rapidapi.com/statistics"
    querystring = {"country":"Indonesia"}
    headers = {
        'x-rapidapi-host': "covid-193.p.rapidapi.com",
        'x-rapidapi-key': "7b039c71a9msh11121f885beb4e5p15166bjsn0807437126b5"
        }
    response = requests.request("GET", url, headers=headers, params=querystring).json()
    data = response['response']
    d =data[0]
    # print(d)
    context = {
        'all' : d['cases']['total'],
        'recovered' : d['cases']['recovered']
    }
    return render(request, 'main/home.html',context)

def formFeedback(request):
    form = FeedbackForm()
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/feedbacks')
    context = {
        'form' : form,
    }
    return render(request, 'main/feedbackForm.html',context)

def listFeedback(request):
    feedbacks = Feedback.objects.all()
    return render (request,'main/feedbackList.html',{'feedbacks':feedbacks})

main/templates/main/feedbackForm.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block meta %}
<header>
    <link rel="stylesheet" href="{% static 'css/homefeed.css' %}"/>
    <div class="cover2" >
    </div>
</header>
{% endblock meta %}

{% block content %}
<div class="container" style="margin-top: 50px; margin-bottom: 200px;">
    <div class="container-fluid">
            <h2 class="featurette-heading" style="color: #2C175D;"><b>Give Us Your Feedback</b></h2>
            <hr class="mt-0 mb-4">
            <form method='POST'>
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn" style="background-color: #2C175D; color: white;" ><b>Submit</b></button>
            <a type="button" class="btn btn-danger" href="{% url 'main:home' %}"><b>Back</b></a>
        </form>
    </div>
</div>

{% endblock content %}

main/templates/main/feedbackList.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block meta %}
<header>
    <link rel="stylesheet" href="{% static 'css/homefeed.css' %}"/>
    <div class="cover2" >
    </div>
</header>
{% endblock meta %}

{% block content %}
<div class="container" style="margin-top: 50px; margin-bottom: 200px;">
    <div class="container-fluid">
        <div class="d-flex bd-highlight mb-3">
            <div class="p-2 bd-highlight">
                <h2 class="featurette-heading" style="color: #2C175D;"><b>Give Us Your Feedback</b></h2>
            </div>
            <div class="ml-auto p-2 bd-highlight">  
                <a type="button" class="btn" href="{% url 'main:feedbackform' %}" style="background-color: #2C175D; color: white;">Add Feedback</a>
            </div>
          </div>
        
        <hr class="mt-0 mb-4">
        {% for i in feedbacks %}
        <div class="card text-white" style="background-color: #2C175D; margin-top: 20px; border-radius: 10px;">
            <div class="card-header border-bottom border-light"><b>{{i.nama}}</b></div>
            <div class="card-body">
              <p class="card-text">{{i.feedbackUser}}</p>
            </div>
          </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<header> 
  <link rel="stylesheet" href="{% static 'css/homefeed.css' %}"/>
  <div class="cover" style="background-image: url(static/image/tst.png);">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-6">
          <img src="{% static 'image/Group19.png' %}" class="img-fluid" alt="Responsive image" style="width: 10500px;">
        </div>
        <div class="col-md-6">
          <p id="pertama">LET’S HELP  RECOVER THE EARTH</p>
          <p id="kedua">SAVE YOURSELF, SAVE THE WORLD</p>
          <p id="ketiga">Coronavirus disease (COVID-19) is an infectious disease caused by a new virus</p>
          <div class="d-flex justify-content-start">
            <div class="tombol">
              <a href="https://www.youtube.com/watch?v=0dAoCfgAQw8" class="btn btn-danger mr-3 btn-lg" >Watch Here</a>
              <a href="https://www.youtube.com/watch?v=0dAoCfgAQw8" class="btn btn-outline-warning btn-lg">Learn More</a>
            </div>
          </div>
          <div class="d-flex justify-content-start" style="margin-top: 20px;">
            <div class="card text-center mr-4 " id="kartu" style="width: 18rem; background-color: #4029BB; border-radius: 20px; box-shadow: 3px 6px rgba(0, 0, 0, 0.3);">
              <div class="card-body">
                <p id="kelima" >Active</p>
                <h1 id="keenam">{{ all }}</h1>
              </div>
            </div>
            <div class="card text-center" id="kartu" style="width: 18rem; background-color: #4029BB; border-radius: 20px; box-shadow: 3px 6px rgba(0, 0, 0, 0.3);">
              <div class="card-body">
                <p id="kelima">Recovered</p>
                <b id="ketujuh">{{ recovered }}</b>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>
{% endblock meta %}

{% block content %}
<div class="container">
  <div class="container-fluid">
    <div class="row">
      <div class="row flex-row-reverse">
        <div class="col-md-6">
            <img src="{% static 'image/Group38.png' %}" class="img-fluid" alt="Responsive image" >
        </div>
        <div class="col-md-6 ">
          <p id="first">Apa Itu COVID-19?</p>
          <p id="second">Penyakit yang disebabkan oleh virus severe acute respiratory syndrome coronavirus 2 (SARS-CoV-2).</p>
        </div>
      </div>
        <div class="col-md-6" >
          <img src="{% static 'image/Group35.png' %}" class="img-fluid" alt="Responsive image" >
        </div>
        <div class="col-md-6">
          <p id="first">Gejala umum Covid19 apa saja?</p>
          <p id="second">
            Gejala umumnya demam (suhu tubuh diatas 38°C), batuk kering,
            dan sesak napas</p>
        </div>
        <div class="row flex-row-reverse">
          <div class="col-md-6" >
            <img src="{% static 'image/Group46.png' %}" class="img-fluid" alt="Responsive image">
          </div>
          <div class="col-md-6" >
            <p id="first">Apa lagi gejala Covid19 yang lain ?</p>
            <p id="second">Gejala lainnya mudah lelah, nyeri otot, nyeri dada, sakit tenggorokan, sakit kepala, mual / muntah, diare, hingga hilangnya kemampuan mengecap rasa / mencium bau.</p>
          </div>
        </div>
      <div class="col-md-6" >
          <img src="{% static 'image/Group36.png' %}" class="img-fluid" alt="Responsive image">
      </div>
      <div class="col-md-6">
        <p id="first">Apakah ada faktor risiko Covid-19?</p>
        <p id="second">
          Covid19 dapat menyerang siapa saja, tetapi akan lebih berbahaya/bahkan fatal jika menyerang orang lanjut usia, ibu hamil, perokok, dan orang dengan imun lemah.</p>
      </div>
      <div class="row flex-row-reverse" style="margin-bottom: 100px;">
        <div class="col-md-6">
            <img src="{% static 'image/Group40.png' %}" class="img-fluid" alt="Responsive image">
        </div>
        <div class="col-md-6">
          <p id="first">Pemeriksaan apa yang harus saya lakukan?</p>
          <p id="second">Rapid test, Tes PCR (polymerase chain reaction) / swab test, CT Scan, atau tes darah lengkap.</p>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}